export const universitiesByCity = {
  aberdeen: ["Robert Gordon University", "University of Aberdeen"],
  aberystwyth: ["Aberystwyth University"],
  bangor: ["Bangor University"],
  bath: ["Bath Spa University", "University of Bath"],
  belfast: ["Queen's University Belfast", "Ulster University"],
  birmingham: [
    "Aston University",
    "Birmingham City University",
    "Birmingham Newman University",
    "University College Birmingham",
    "University of Birmingham",
  ],
  bournemouth: [
    "Arts University Bournemouth",
    "Bournemouth University",
    "Health Sciences University",
  ],
  brighton: ["University of Brighton", "University of Sussex"],
  bristol: ["University of Bristol", "University of the West of England"],
  cambridge: ["Anglia Ruskin University", "University of Cambridge"],
  canterbury: [
    "Canterbury Christ Church University",
    "University for the Creative Arts",
    "University of Kent",
  ],
  cardiff: [
    "Cardiff Metropolitan University",
    "Cardiff University",
    "University of South Wales",
  ],
  chester: ["University of Chester"],
  coventry: ["Coventry University", "University of Warwick"],
  derby: ["University of Derby"],
  dundee: ["Abertay University", "University of Dundee"],
  durham: ["Durham University"],
  edinburgh: [
    "Edinburgh Napier University",
    "Heriot-Watt University",
    "Queen Margaret University",
    "University of Edinburgh",
  ],
  essex: ["Anglia Ruskin University", "University of Essex"],
  exeter: ["University of Exeter"],
  falmouth: ["Falmouth University", "University of Exeter"],
  glasgow: [
    "Glasgow Caledonian University",
    "University of Glasgow",
    "University of Strathclyde",
  ],
  gloucestershire: ["Hartpury University", "University of Gloucestershire"],
  hanley: ["University of Staffordshire"],
  hertfordshire: ["University of Hertfordshire"],
  huddersfield: ["University of Huddersfield"],
  hull: ["University of Hull"],
  keele: ["Keele University"],
  kent: [
    "Canterbury Christ Church University",
    "University for the Creative Arts",
    "University of Kent",
  ],
  kingston: ["Kingston University"],
  lancaster: ["Lancaster University", "University of Cumbria"],
  leeds: [
    "Leeds Arts University",
    "Leeds Beckett University",
    "Leeds Trinity University",
    "University of Leeds",
  ],
  leicester: ["De Montfort University", "University of Leicester"],
  lincoln: ["Lincoln Bishop University", "University of Lincoln"],
  liverpool: [
    "Liverpool Hope University",
    "Liverpool John Moores University",
    "University of Liverpool",
  ],
  london: [
    "Birkbeck, University of London",
    "Brunel University of London",
    "City St George's, University of London",
    "Goldsmiths, University of London",
    "Imperial College London",
    "King's College London",
    "Kingston University",
    "London Metropolitan University",
    "London School of Economics",
    "London South Bank University",
    "Middlesex University",
    "Northeastern University London",
    "Queen Mary University of London",
    "Ravensbourne University London",
    "Regent's University London",
    "Royal Holloway, University of London",
    "Royal Veterinary College",
    "SOAS University of London",
    "St Mary's University, Twickenham",
    "University College London",
    "University of East London",
    "University of Greenwich",
    "University of Roehampton",
    "University of the Arts London",
    "University of West London",
    "University of Westminster",
  ],
  loughborough: ["Loughborough University"],
  manchester: [
    "Manchester Metropolitan University",
    "University of Manchester",
    "University of Salford",
  ],
  newcastle: ["Newcastle University", "Northumbria University"],
  northampton: ["University of Northampton"],
  norwich: ["Norwich University of the Arts", "University of East Anglia"],
  nottingham: ["Nottingham Trent University", "University of Nottingham"],
  oxford: ["Oxford Brookes University", "University of Oxford"],
  plymouth: [
    "Arts University Plymouth",
    "Plymouth Marjon University",
    "University of Plymouth",
  ],
  portsmouth: ["University of Portsmouth"],
  preston: ["University of Lancashire"],
  reading: ["University of Reading"],
  sheffield: ["Sheffield Hallam University", "University of Sheffield"],
  southampton: ["Southampton Solent University", "University of Southampton"],
  stirling: ["University of Stirling"],
  staffordshire: ["Keele University", "University of Staffordshire"],
  surrey: ["University for the Creative Arts", "University of Surrey"],
  swansea: ["Swansea University", "University of Wales Trinity Saint David"],
  uxbridge: ["Brunel University of London"],
  warwick: ["University of Warwick"],
  windsor: ["Royal Holloway, University of London"],
  wolverhampton: ["University of Wolverhampton"],
  york: ["University of York", "York St John University"],
};

const knownUniversities = new Set(Object.values(universitiesByCity).flat());

export function getUniversities(slug) {
  return universitiesByCity[slug] || [];
}

export function isUniversity(name) {
  return knownUniversities.has(name);
}
